#############
#Rjml: a faster R program for performing JML analyses
#############
if(!require("argparser"))
{
install.packages("argparser_0.7.1.tar.gz",repos=NULL,type="source")
}
if(!require("iterators"))
{
install.packages("iterators_1.0.8.tar.gz",repos=NULL,type="source")
}
if(!require("foreach"))
{
install.packages("foreach_1.5.2.tar.gz",repos=NULL,type="source")
}
if(!require("doParallel"))
{
install.packages("doParallel_1.0.17.tar.gz",repos=NULL,type="source")
}
if(!require("Rcpp"))
{
install.packages("Rcpp_1.0.9.tar.gz",repos=NULL,type="source")
}
if(!require("RcppArmadillo"))
{
install.packages("RcppArmadillo_0.11.2.4.0.tar.gz",repos=NULL,type="source")
}
if(!require("Cjml1"))
{
install.packages("Cjml1_1.0.tar.gz",repos=NULL,type="source")
}
library(parallel)
library(foreach)
library(doParallel)
library(Cjml1)
library(argparser, quietly=TRUE)
p <- arg_parser("Rjml: a faster R program for performing JML analyses")
p <- add_argument(p, "phy", help="input: sequence file with phylip fromat", type="character" )
p <- add_argument(p, "alpha", help="JM Lsignificance level", type="character" )
p <- add_argument(p, "ncores", help="Number of cores used in JML", type="character" )
argv <- parse_args(p)
input <- argv$phy
inputalpha <- as.numeric(argv$alpha)
inputcores <- as.numeric(argv$ncores)
make.seqmat<-function(seqlist)
{
n=length(seqlist[[1]])
s=length(seqlist)
seqmat=vector()
seqv=vector()
nam=names(seqlist)
for(i in 1:length(seqlist))
{
seqmat=rbind(seqmat,seqlist[[i]])
seqv=c(seqv,paste(seqlist[[i]],collapse=""))
}
rownames(seqmat)=nam
return(seqmat)
}
make.seqlist<-function(seqmat)
{
n=dim(seqmat)[2]
s=dim(seqmat)[1]
sn=rownames(seqmat)
seqlist=list()
for(i in 1:s)
{
seqlist[[i]]=seqmat[i,]
}
if(length(sn)>0)
{
names(seqlist)=sn
}
return(seqlist)
}
seqvec2seqlist<-function(seqvec)
{
s=length(seqvec)
sn=names(seqvec)
seqlist=list()
for(i in 1:s)
{
seqlist[[i]]=strsplit(seqvec[i],"")[[1]]
}
if(length(sn)>0)
{
names(seqlist)=sn
}
return(seqlist)
}
DANbin2seqlist<-function(seqmat)
{
n=dim(seqmat)[2]
s=dim(seqmat)[1]
sn=rownames(seqmat)
seqlist=list()
for(i in 1:s)
{
seqlist[[i]]=as.vector(as.character(seqmat[i,]))
}
if(length(sn)>0)
{
names(seqlist)=sn
}
return(seqlist)
}
sps.seq.dist<-function(dnamat,method="raw")
{
seqIDlist=list()
sps=sort(unique(as.character(dnamat[,3]))) 
for(i in 1:length(sps))
{
ids=which(dnamat[,3]==sps[i])
seqIDlist[[i]]=ids
}
dnav=dnamat[,5] 
if(method=="DNAbin")
{
seqs=seqvec2seqlist(dnav)
seqm=make.seqmat(seqs)
dnas=as.DNAbin(seqm) 
seqmat=as.matrix(dist.dna(dnas))
}
if(method=="raw")
{
seqs=seqvec2seqlist(dnav)
seqmat=pairwise.difference(seqs,gaps.removed=TRUE)
}
spsmat=matrix(0,length(sps),length(sps))
for(i in 1:(length(sps)-1))
{
for(j in (i+1):length(sps))
{
ids1=which(dnamat[,3]==sps[i])
ids2=which(dnamat[,3]==sps[j])
spsmat[i,j]=spsmat[j,i]=min(seqmat[ids1,ids2])
}
}
colnames(spsmat)=rownames(spsmat)=sps
return(list(spsmat=spsmat,seqmat=seqmat))
}
sps.seq.dist1<-function(dnamat,spsv,method="raw")
{
dnav=dnamat[,5] 
if(method=="DNAbin")
{
seqs=seqvec2seqlist(dnav)
seqm=make.seqmat(seqs)
dnas=as.DNAbin(seqm) 
seqmat=as.matrix(dist.dna(dnas))
}
if(method=="raw")
{
seqs=seqvec2seqlist(dnav)
seqmat=pairwise.difference(seqs,gaps.removed=TRUE)
}
spsmat=matrix(0,length(spsv),length(spsv))
for(i in 1:(length(spsv)-1))
{
for(j in (i+1):length(spsv))
{
ids1=which(dnamat[,3]==spsv[i])
ids2=which(dnamat[,3]==spsv[j])
spsmat[i,j]=spsmat[j,i]=min(seqmat[ids1,ids2])
}
}
colnames(spsmat)=rownames(spsmat)=spsv
return(list(spsmat=spsmat,seqmat=seqmat))
}
sps.seq.dist2<-function(dnamat,spsv,method="raw")
{
dnav=dnamat[,5] 
if(method=="DNAbin")
{
seqs=seqvec2seqlist(dnav)
seqm=make.seqmat(seqs)
dnas=as.DNAbin(seqm) 
seqmat=as.matrix(dist.dna(dnas))
}
if(method=="raw")
{
seqs=seqvec2seqlist(dnav)
seqmat=make.seqmat(seqs)
seqmat=Cjml1::PD(seqmat)
}
spsmat=Cjml1::sps_PD(spsv,dnamat[,3],seqmat) 
colnames(spsmat)=rownames(spsmat)=spsv 
colnames(seqmat)=rownames(seqmat)=as.character(dnamat[,3]) 
return(list(spsmat=spsmat,seqmat=seqmat))
}
fasta2seqvec<-function(path,header=TRUE)
{
one=readLines(path)
if(header==TRUE)
{
two=one[-1]
}else
{
two=one
}
seqs=vector()
sname=vector()
num=length(two)
for(i in 1:num)
{
ids=unlist(gregexpr(" ",two[i],fixed=TRUE))
thisn=substr(two[i],1,ids[1]-1)
thisseq=substr(two[i],ids[length(ids)]+1,nchar(two[i]))
seqs[i]=thisseq
sname[i]=thisn
}
names(seqs)=sname
return(seqs)
}
pairwise.difference<-function(dat,gaps.removed=TRUE)
{
n=length(dat[[1]])
s=length(dat)
seqmat=vector()
seqv=vector()
for(i in 1:length(dat))
{
seqmat=rbind(seqmat,dat[[i]])
seqv=c(seqv,paste(dat[[i]],collapse=""))
}
hapn=length(unique(seqv))
hp=table(seqv)
p=hp/sum(hp)
hapdiv=(1-sum(p^2))*s/(s-1)
gaps=vector()
polys=vector()
for(i in 1:n)
{
one=seqmat[,i]
if(length(grep("-",one))==0)
{
if(length(unique(one))>1)
{
polys=c(polys,i)
}
}else
{
gaps=c(gaps,i)
}
}
if(length(gaps)>0 & gaps.removed==TRUE)
{
nsite=n-length(gaps)
}else
{
nsite=n
}
ND=matrix(0,s,s)
for(i in 1:(s-1))
{
for(j in (i+1):s)
{
if(length(gaps)>0 & gaps.removed==TRUE)
{
one=seqmat[i,-gaps]
two=seqmat[j,-gaps]
}else
{
one=seqmat[i,]
two=seqmat[j,]
}
kij=length(which(one!=two))
ND[i,j]=ND[j,i]=kij/(nsite+1e-300)
ND[i,j]=ND[j,i]=kij/(n+1e-300)
}
}
nam=names(dat)
colnames(ND)=rownames(ND)=nam
return(ND)
}
cl <- makeCluster(inputcores)
registerDoParallel(cl)
this=input 
ALPHA=inputalpha 
f=list.files()
f=f[grep("RepSeqs",f)]
f1=gsub("[:A-z:]","",f)
f1=gsub(".","",f1,fixed=TRUE)
r=as.numeric(f1)+1
f2=vector()
for(i in 1:length(r))
{
f2=c(f2,f[which(r==i)])
}
f=f2
seqs=fasta2seqvec(f[1])
nam=names(seqs)
sps=gsub("[:0-9:]","",nam)
dnamat=cbind(NA,NA,sps,nam,seqs)
dmat=sps.seq.dist(dnamat)
spsmat=array(0,dim=c(dim(dmat$spsmat),length(f)))
seqmat=array(0,dim=c(dim(dmat$seqmat),length(f)))
spsv=colnames(dmat$spsmat)
read.seqmat2<-function(i)
{
seqs=fasta2seqvec(f[i])
nam=names(seqs)
sps=gsub("[:0-9:]","",nam)
dnamat=cbind(NA,NA,sps,nam,seqs)
dmat=sps.seq.dist2(dnamat,spsv) 
return(list(spsmat=dmat$spsmat,seqmat=dmat$seqmat))
}
out=foreach(i=1:length(f))%dopar%read.seqmat2(i) 
stopCluster(cl) 
for(i in 1:length(out))
{
spsmat[,,i]=out[[i]][[1]]
seqmat[,,i]=out[[i]][[2]]
}
sps=colnames(dmat$spsmat)
pair=vector()
pmat=vector()
for(i in 1:(length(sps)-1))
{
for(j in (i+1):length(sps))
{
pair=c(pair,paste(sps[i],sps[j],sep="-"))
pmat=cbind(pmat,spsmat[i,j,])
}
}
colnames(pmat)=pair
write.table(pmat,"Distributions_Rjml.csv",sep=",",col.names=TRUE,row.names=FALSE)
seqs=fasta2seqvec(this)
nam=names(seqs)
sps1=gsub("[:0-9:]","",nam)
seqv=nam
obs_dnamat=cbind(NA,NA,sps1,nam,seqs)
bmat=sps.seq.dist1(obs_dnamat,spsv)
obs_spsmat=bmat$spsmat
obs_seqmat=bmat$seqmat
pmat1=vector()
pair=vector()
for(i in 1:(length(spsv)-1))
{
for(j in (i+1):length(spsv))
{
thisp=paste(spsv[i],spsv[j],sep="-")
pair=c(pair,thisp)
spr=sort(spsmat[i,j,],decreasing=FALSE)
prob=(which(spr>obs_spsmat[i,j])[1])/dim(spsmat)[3] #following JML logic,
pmat1=rbind(pmat1,c(thisp,obs_spsmat[i,j],prob))
}
}
rownames(pmat1)=pair
colnames(pmat1)=c("Comparison","minDist","Probability")
write.table(pmat1,"Probabilities_Rjml.csv",sep=",",row.names=TRUE,col.names=TRUE)
pmat2=c("Species pair","Seq1","Seq2","Distance","Probability")
pair=vector()
flag=0
for(i in 1:(length(seqs)-1))
{
for(j in (i+1):length(seqs))
{
id1=which(spsv==obs_dnamat[i,3])
id2=which(spsv==obs_dnamat[j,3])
if(spsv[id1]!=spsv[id2])
{
spr=sort(spsmat[id1,id2,],decreasing=FALSE)
if(obs_seqmat[i,j]<spr[as.integer(ALPHA*length(spr))+1]) 
{
prob=(which(spr>obs_seqmat[i,j])[1])/dim(spsmat)[3] 
thisp=paste(spsv[id1],spsv[id2],sep="-")
pair=c(pair,thisp)
if(is.na(obs_dnamat[i,4]))
{
v1=i
}else
{
v1=obs_dnamat[i,4]
}
if(is.na(obs_dnamat[j,4]))
{
v2=i
}else
{
v2=obs_dnamat[j,4]
}
pmat2=rbind(pmat2,c(thisp,v1,v2,obs_seqmat[i,j],prob))
flag=1
}
}
}
}
if(flag==0)
{
pmat3=as.data.frame(t(as.matrix(pmat2)))
}else
{
pmat3=as.data.frame(pmat2)
}
write.table(pmat3,"Results_Rjml.csv",sep=",",row.names=FALSE,col.names=FALSE)
file.remove(f)
